version: '3.8'

services:
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      default:
        ipv4_address: 172.20.0.2

volumes:
  mongodb_data:

networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16
